version: "3.7"

services:
  db:
    image: postgres:12.0-alpine
    volumes:
      - ./postgres_data:/var/lib/postgresql/data/
    environment:
      - POSTGRES_USER=django_courses_user
      - POSTGRES_PASSWORD=django_courses_password
      - POSTGRES_DB=django_courses_dev
    ports:
      - "5432:5432"
volumes:
  postgres_data: