version: "3.8"

services:
  web:
    container_name: web
    build: .
    command: python manage.py runserver 0.0.0.0:8000
    volumes:
      - .:/usr/src/app/
    ports:
      - "1337:8000"
    env_file:
      - .env.dev
    depends_on:
      - db
      - redis
  db:
    container_name: db
    image: postgres:12.0-alpine
    volumes:
      - postgres_data:/var/lib/postgresql/data/
    environment:
      - POSTGRES_USER=django_courses_user
      - POSTGRES_PASSWORD=django_courses_password
      - POSTGRES_DB=django_courses_dev
    ports:
      - "5432:5432"
  redis:
    container_name: redis
    image: redis:alpine
  celery:
    container_name: celery
    build: .
    command: celery -A django_courses worker -l INFO
    volumes:
      - .:/usr/src/app/
    env_file:
      - .env.dev
    depends_on:
      - redis
  celery-beat:
    container_name: celery-beat
    build: .
    command: celery -A django_courses beat -l INFO
    volumes:
      - .:/usr/src/app/
    env_file:
      - .env.dev
    depends_on:
      - redis
volumes:
  postgres_data: