# Generated by Django 3.2.12 on 2022-03-22 09:46

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('lectures', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='hometask',
            name='average_mark',
            field=models.FloatField(blank=True, default=0.0, verbose_name='Средняя отметка'),
            preserve_default=False,
        ),
    ]
